# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/populartimes/ChIJ1VzdXJSjfDURDEgP7ojk8-g
Accept: application/json

###

GET http://127.0.0.1:8000/sensors
Accept: application/json

###
